version: '3.7'

services:
  mongodb:
    image: mongo:4.4
    container_name: girder-mongodb
    restart: always
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db

  girder:
    build:
      context: ./girder/
      dockerfile: Dockerfile
      args:
        GIRDER_CFG_FILE: girder.prod.cfg
    container_name: girder
    restart: always
    ports:
      - "8080:8080"
    links:
      - "mongodb:mongodb"
    command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder

  nginx:
    build: ./girder/nginx
    container_name: girder-nginx
    restart: always
    volumes:
      - ./girder:/girder
      - static_volume:/girder/static
      - /opt/certs:/a
    ports:
      - 8088:8088
    depends_on:
      - girder
  
  client:
    container_name: ninjato-frontend-dev
    build:
      context: ./client/
      dockerfile: Dockerfile-prod
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/certs:/a  
    ports:
      - 443:443      
      - 80:80
    depends_on:
      - girder
    links:
      - girder       
    restart: always

volumes:
  mongodb_data:
  static_volume:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/28

