version: '3.7'

services:
  mongodb:
    image: mongo:4.4
    container_name: girder-mongodb
    restart: always
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db

  girder:
    build:
      context: .
      dockerfile: Dockerfile      
      args:
        GIRDER_CFG_FILE: girder.prod.cfg
        ASSET_STORE_DATA_DIR: data
    container_name: girder
    restart: always
    ports:
      - "8080:8080"
    links:
      - "mongodb:mongodb"
    command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder

  nginx:
    build: ./nginx
    container_name: girder-nginx
    restart: always
    volumes:
      - .:/girder
      - static_volume:/girder/static
      - /opt/certs:/a
    ports:
      - 8080:8080
    depends_on:
      - girder

volumes:
  mongodb_data:
  static_volume:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/28
